# permissions for end users to view yoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yo-viewer-role
rules:
- apiGroups:
  - aashwin.yo.com
  resources:
  - yoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aashwin.yo.com
  resources:
  - yoes/status
  verbs:
  - get
